### ISSUE TITLE
Add Test Coverage for backend

### ISSUE THREAD

**Issue by 26tanishabanik** [iptables-viz/iptables-viz#13]
**Overview:**
This issue aims to enhance the test coverage of the backend codebase by writing test cases for handler functions of the API and utility functions.

**Tasks:** 

- [ ] Write test cases for different scenarios (positive, negative, edge cases)
- [ ] Ensure proper test coverage
- [ ] Generate code coverage reports.
