### ISSUE TITLE
Add a docker-compose file

### ISSUE THREAD

**Issue by 26tanishabanik** [iptables-viz/iptables-viz#15]
**Overview:**
The goal of this issue is to create a Docker Compose configuration file for the project.

**Tasks:**

- [ ] Write a docker-compose.yaml file in the project's root directory
- [ ] Test the Docker Compose configuration locally to ensure that the services start correctly and communicate as expected
- [ ] Update the project's README.md file to provide instructions on using Docker Compose to run the project

**Comment by devsargam** [comment]
@26tanishabanik  can you elaborate a bit on what should be there in the docker compose?

**Comment by 26tanishabanik** [comment]
> @26tanishabanik can you elaborate a bit on what should be there in the docker compose?

@devsargam , Thanks for your response
I believe the docker-compose file should include both the backend and frontend services exposed on some container ports, you can refer the [kubernetes manifests](https://github.com/iptables-viz/iptables-viz/blob/main/manifests/kubernetes-deploy.yaml) to better understand how and where those ports are being exposed

**Comment by 26tanishabanik** [comment]
@devsargam , Let me know if you have any further questions

**Comment by devsargam** [comment]
@26tanishabanik so far I don't have any further questions.
Can you assign me this issue?
I have almost no experience with k8s but have enough with docker so I think I can easily accomplish it.

**Comment by 26tanishabanik** [comment]
@devsargam ,sure, once you raise a PR for this issue, we will assign it to you

**Comment by 26tanishabanik** [comment]
@devsargam , are you still working on this issue?

**Comment by devsargam** [comment]
@26tanishabanik I am working on this one but I was confused about issue #19

And can you help me with running steps. I am on a mac and `systemd` is not there so when using Dockerfile I am encountering few erros

**Comment by 26tanishabanik** [comment]
Sorry for the delay, @devsargam 
For mac issue, you can install a hypervisor and try installing a ubuntu VM on top of it, maybe

**Comment by 26tanishabanik** [comment]
> @26tanishabanik I am working on this one but I was confused about issue #19
> 
> And can you help me with running steps. I am on a mac and `systemd` is not there so when using Dockerfile I am encountering few erros

@neelanjan00 , can you check for the node commands in the Dockerfile?

**Comment by 26tanishabanik** [comment]
> Sorry for the delay, @devsargam For mac issue, you can install a hypervisor and try installing a ubuntu VM on top of it, maybe

@devsargam , can you share the errors regarding `systemd`?

**Comment by devsargam** [comment]
@26tanishabanik there is no `systemd` & `systemctl` in my system. Also, I can't use scripts due to incompatible os. So, I am unable to take this issue further. Sorry!

**Comment by neelanjan00** [comment]
Docker Compose file won't use systemd, we just need to run the docker container as part of the Docker Compose. It's just a script. The container is already there.
