### ISSUE TITLE
Add a helm chart for k8s platform

### ISSUE THREAD

**Issue by 26tanishabanik** [iptables-viz/iptables-viz#16]
**Overview:**
The goal of this issue is to create a Helm chart for the project to simplify deployment and management of the application in a Kubernetes environment.

**Tasks:**

- [ ] Create a helm chart with all the necessary configurations under a new folder called `charts`
- [ ] Update the documentation explaining how to use the Helm chart
- [ ] Test the Helm chart locally in a Kubernetes environment to ensure that it deploys the application correctly

**Comment by Rajdeep1311** [comment]
Can I help ma'am?

**Comment by 26tanishabanik** [comment]
> Can I help ma'am?

@Rajdeep1311 , please feel free to take up this issue

**Comment by 26tanishabanik** [comment]
@Rajdeep1311 , will you be working on this issue?

**Comment by Rajdeep1311** [comment]
Yes ma'am I would like to give it a shot

**Comment by 26tanishabanik** [comment]
> Yes ma'am I would like to give it a shot

Sure, whenever you raise a PR, we will assign this issue to you

**Comment by 26tanishabanik** [comment]
@Rajdeep1311 , are you still working on this issue?

**Comment by Rajdeep1311** [comment]
Yes ma'am I am trying but I have a busy schedule.
